image: node:12.22.1-alpine3.12

cache:
  policy: pull-push
  paths:
    - node_modules/

before_script:
  - npm install

build:
  stage: build
  script:
    - npm run compile
  artifacts:
    paths:
      - "./out/"
    untracked: false

test:
  stage: test
  image: node:12.22.1-buster
  script:
    - |
      apt update
      apt install -y libasound2 libgbm1 libgtk-3-0 libnss3 xvfb
      xvfb-run -a npm run test

deploy:
  stage: deploy
  only:
    - tags
  script:
    - |
      npm run package
      npm run publish
